[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Easy-DLM"
version = "1.0"
description = ""
authors = [{ name="SinouÃ© GAD" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [

]

[tool.uv]
package = false